export const routes = {
  ui: {
    indexRoute: "/",
    signIn: "/auth/sign-in",
    areas: "/area",
    category: "/category",
    orders: "/orders",
    users: "/users",
    feedback: "/feedback",
    areaDetails: (id: string | number) => `area/${id}`,
    categoryDetails: (id: string | number) => `category/${id}`,
    orderDetails: (id: string | number, number?: string | number) =>
      number ? `orders/${id}?number=${number}` : `orders/${id}`,
    userDetails: (id: string | number) => `users/${id}`,
  },

  api: {
    getArea: "areas",
    searchArea: "areas?name=ashtead",
    editArea: (id: string | number) => `areas/${id}`,
    deleteArea: (id: string | number) => `areas/${id}`,
    getAreaSlots: (id: string | number) => `areas/${id}/slots`,
    markSlotActive: (id: string) => `slots/${id}/mark-as-active`,
    markSlotInactive: (id: string) => `slots/${id}/mark-as-inactive`,
    createSlot: "slots",
    updateSlot: (id: string) => `slots/${id}`,
    login: "login-check",
    getPostcodes: (id: string) => `areas/${id}/postcodes`,
    createPostcode: "postcodes",
    markPostcodeActive: (id: string) => `postcodes/${id}/mark-as-active`,
    markPostcodeInactive: (id: string) => `postcodes/${id}/mark-as-inactive`,
    getItemCategories: "item-categories/admin-list",
    createItemCategory: "item-categories",
    updateItemCategory: (id: string) => `item-categories/${id}`,
    deleteItemCategory: (id: string) => `item-categories/${id}`,
    getItemCategoryDetails: (id: string) => `item-categories/${id}/items`,
    createItems: "items",
    deleteItems: (id: string) => `items/${id}`,
    updateItems: (id: string) => `items/${id}`,
    getOrders: (page: number | string = 1) => `orders/admin-list?page=${page}`,
    getOrderDetails: (id: string) => `orders/${id}/admin-detail`,
    getOrderItems: (id: string) => `orders/${id}/order-items`,
    cancelOrder: (id: string) => `orders/${id}/mark-as-cancelled`,
    finaliseOrder: (id: string) => `orders/${id}/finalise`,
    markDelivered: (id: string) => `orders/${id}/mark-as-delivered`,
    createRegularItem: "order-items",
    createOpenItem: "order-items/open-item",
    deleteOrderItem: (id: string) => `order-items/${id}`,
    updateOrderItem: (id: string) => `order-items/${id}`,
    getItemCategoryById: (id: string) => `item-categories/${id}`,
    getUsers: (page: number | string = 1) => `users/admin-list?page=${page}`,
    getUserDetails: (id: string) => `users/${id}/admin-detail`,
    getUserOrdersHistory: (id: string) => `users/${id}/orders-history`,
    getFeedback: (page: number | string = 1) =>
      `feedback/admin-list?page=${page}`,
    markFeedbackFeatured: (id: string) => `feedbacks/${id}/mark-as-featured`,
    markFeedbackUnfeatured: (id: string) =>
      `feedbacks/${id}/mark-as-unfeatured`,
  },
};
